openapi: 3.0.0
info:
  description: API for the spotify mood tracker backend
  version: "1.0.0-oas3"
  title: Spotify Mood Tracker
  contact:
    email: dreiclark@gmail.com
    url: 'http://idonthaveawebsite.com'
paths:
  /api/request_token:
    get:
      summary: Get access and refresh tokens- only needs to be done once
      operationId: getToken
      responses:
        '200':
          description: Success
        '400':
          description: Error
  /api/update_tracks:
    get:
      summary: Trigger database update by fetching new recently played tracks
      operationId: fetchNewTracks
      responses:
        '200':
          description: Successful update
        '201':
          description: No new tracks added
        '400':
          description: Error on update
  /api/get_tracks_by_date:
    get:
      summary: Get specified tracks from the database
      parameters:
        - in: query
          name: startDate
          required: true
          description: |
            specify the earliest play date you want to include 
            in the fetch in the format '2017-07-21'
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          required: true
          description: |
            specify the latest play date you want to include 
            in the fetch in the format '2017-07-21'
          schema:
            type: string
            format: date
            default: now
      operationId: getTracks
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                type: array  
                items:
                  $ref: '#/components/schemas/track'
        '204':
          description: No query matches
        '500':
          description: Internal server error
  /api/get_tracks_by_days:
    get:
      summary: Get specified tracks from the database
      parameters:
        - in: query
          name: days
          required: true
          description: |
            get tracks from the past x days
          schema:
            type: string
            format: number
            default: '1'
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/track'
        '204':
          description: No query matches
        '500':
          description: Internal server error
  /api/get_mean_valence_by_days:
    get:
      summary: Get mean valence over the past x days
      parameters:
        - in: query
          name: days
          required: true
          description: |
            get mean valence from the past x days
          schema:
            type: string
            format: number
            default: '1'
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                type: number
                items:
                  $ref: '#/components/schemas/track'
        '204':
          description: No query matches
        '500':
          description: Internal server error
servers:
  - url: 'https://virtserver.swaggerhub.com/Adrian-David/spotify-mood-tracker/1.0.0'
components:
  schemas:
    track:
      type: object
      required:
        - title
        - spotifyid
        - valence
        - date
      properties:
        title:
          type: string
          example: Here Comes The Sun
        spotifyid:
          type: string
          example: 4OT8GH9u9Gx7ydJ49ULunN
        valence:
          type: number
          format: float
          example: 0.45
        date:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'